server:
  port: 80

spring:
  application:
    name: mmd-gateway
  #把本服务注册进下面的nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
